name: Autobump Main Version
on:
  push:
    branches:
      - main
jobs:
  Autobump-Main-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Autobump
        id: version
        uses: paulhatch/semantic-version@v5.2.1
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"
          enable_prerelease_mode: false
          debug: false